//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.05 at 11:43:06 AM EEST 
//


package lt.viko.eif.rstankevicius.serverrenting.api.models;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for userDataCheck complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userDataCheck">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hasDedicatedServers" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hasCloudServers" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="amountOfDedicatedServers" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="amountOfCloudServers" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userDataCheck", propOrder = {
    "hasDedicatedServers",
    "hasCloudServers",
    "price",
    "amountOfDedicatedServers",
    "amountOfCloudServers"
})
public class UserDataCheck {

    @XmlElement(defaultValue = "false")
    protected boolean hasDedicatedServers;
    @XmlElement(defaultValue = "false")
    protected boolean hasCloudServers;
    protected float price;
    @XmlElement(defaultValue = "0")
    protected int amountOfDedicatedServers;
    @XmlElement(defaultValue = "0")
    protected int amountOfCloudServers;

    /**
     * Gets the value of the hasDedicatedServers property.
     * 
     */
    public boolean isHasDedicatedServers() {
        return hasDedicatedServers;
    }

    /**
     * Sets the value of the hasDedicatedServers property.
     * 
     */
    public void setHasDedicatedServers(boolean value) {
        this.hasDedicatedServers = value;
    }

    /**
     * Gets the value of the hasCloudServers property.
     * 
     */
    public boolean isHasCloudServers() {
        return hasCloudServers;
    }

    /**
     * Sets the value of the hasCloudServers property.
     * 
     */
    public void setHasCloudServers(boolean value) {
        this.hasCloudServers = value;
    }

    /**
     * Gets the value of the price property.
     * 
     */
    public float getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     */
    public void setPrice(float value) {
        this.price = value;
    }

    /**
     * Gets the value of the amountOfDedicatedServers property.
     * 
     */
    public int getAmountOfDedicatedServers() {
        return amountOfDedicatedServers;
    }

    /**
     * Sets the value of the amountOfDedicatedServers property.
     * 
     */
    public void setAmountOfDedicatedServers(int value) {
        this.amountOfDedicatedServers = value;
    }

    /**
     * Gets the value of the amountOfCloudServers property.
     * 
     */
    public int getAmountOfCloudServers() {
        return amountOfCloudServers;
    }

    /**
     * Sets the value of the amountOfCloudServers property.
     * 
     */
    public void setAmountOfCloudServers(int value) {
        this.amountOfCloudServers = value;
    }

}
